<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>de7b9ce5-ee20-4b4d-8198-f889f1b33fbc</elementGuidId>
    <imagePath></imagePath>
    <name>div_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiGrid-root\ MuiGrid-item\ MuiGrid-grid-xs-12\ MuiGrid-grid-sm-8\ MuiGrid-grid-md-9\ css-tjgi9t"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>