<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e8048f65-3a72-405e-92c1-25d25b2a44f2</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_apple</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/nav[1]/div[1]/ul[1]/li[2]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="horizontal-menu__child-element"]:nth-child(1) &gt; [class="horizontal-menu__element\ is-link\ is-child"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Apple')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Apple</value>
        <webElementGuid>6dafeae7-ab7b-484f-8b06-993b4b18a166</webElementGuid>
    </webElementProperties>
</WebElementEntity>